# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variable name', max_length=128)),
                ('value', models.CharField(blank=True, help_text='Value', max_length=255, null=True)),
                ('json', models.TextField(blank=True, help_text='Json value', null=True)),
            ],
            options={
                'verbose_name': 'Variable',
            },
        ),
    ]
