# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('diablo2.account.sync', 'Can resync Diablo 2 accounts'), ('diablo2.account.sync.all', 'Can resync all Diablo 2 accounts at once'), ('diablo2.character.sync', 'Can resync Diablo 2 characters'), ('diablo2.character.sync.all', 'Can resync all Diablo 2 characters at once'), ('diablo2.moderation.enabled', 'Can access moderation tools')), 'verbose_name': 'Account'},
        ),
    ]
