# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0003_auto_20160129_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('diablo2.account_sync', 'Can resync Diablo 2 accounts'), ('diablo2.account_sync_all', 'Can resync all Diablo 2 accounts at once'), ('diablo2.character_sync', 'Can resync Diablo 2 characters'), ('diablo2.character_sync_all', 'Can resync all Diablo 2 characters at once'), ('diablo2.moderation_enabled', 'Can access moderation tools')), 'verbose_name': 'Account'},
        ),
    ]
