# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0004_auto_20160129_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='characters',
            field=models.IntegerField(default=0, help_text='Number of characters as of last update'),
        ),
    ]
