# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0005_account_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='expansion',
            field=models.BooleanField(default=True, help_text='Character is expansion'),
        ),
    ]
