# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0006_character_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Log message', max_length=255)),
            ],
            options={
                'verbose_name': 'Failed Log',
            },
        ),
        migrations.CreateModel(
            name='GameserverLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time the log entry was generated')),
                ('type', models.CharField(help_text='Log type', max_length=25)),
                ('ip', models.CharField(blank=True, help_text='Player IP address', max_length=16, null=True)),
                ('character_name', models.CharField(blank=True, help_text='Diablo2 character name', max_length=40, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Diablo2 account name', max_length=40, null=True)),
                ('game_id', models.IntegerField(blank=True, default=0, help_text='Game ID', null=True)),
                ('name', models.CharField(blank=True, help_text='Game name', max_length=40, null=True)),
                ('password', models.CharField(blank=True, help_text='Game password', max_length=40, null=True)),
                ('description', models.CharField(blank=True, help_text='Game Description', max_length=75, null=True)),
                ('ladder', models.BooleanField(default=False, help_text='Game is ladder')),
                ('difficulty', models.CharField(blank=True, help_text='Game Difficulty', max_length=10, null=True)),
                ('hardcore', models.BooleanField(default=False, help_text='Game is hardcore')),
                ('expansion', models.BooleanField(default=True, help_text='Game is expansion')),
                ('cclass', models.CharField(blank=True, help_text='Character class', max_length=10, null=True)),
                ('level', models.IntegerField(blank=True, default=1, help_text='Character Level', null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Link to Diablo2 account', null=True, on_delete=django.db.models.deletion.CASCADE, to='diablo2.Account')),
                ('character', models.ForeignKey(blank=True, help_text='Link to Diablo2 character', null=True, on_delete=django.db.models.deletion.CASCADE, to='diablo2.Character')),
            ],
            options={
                'verbose_name': 'Gameserver Log',
            },
        ),
    ]
