# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0007_failedlog_gameserverlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('diablo2_account_sync', 'Can resync Diablo 2 accounts'), ('diablo2_account_sync_all', 'Can resync all Diablo 2 accounts at once'), ('diablo2_character_sync', 'Can resync Diablo 2 characters'), ('diablo2_character_sync_all', 'Can resync all Diablo 2 characters at once'), ('diablo2_moderation_enabled', 'Can access moderation tools'), ('diablo2_log_sync', 'Can sync the gameserver logs'), ('diablo2_log_parse', 'Can parse the gameserver logs')), 'verbose_name': 'Account'},
        ),
        migrations.AlterField(
            model_name='gameserverlog',
            name='type',
            field=models.CharField(choices=[('D2CSCreateEmptyGame', 'Create Game'), ('D2GSCBEnterGame', 'Join Game'), ('D2GSCBLeaveGame', 'Leave Game')], help_text='Log type', max_length=25),
        ),
    ]
