# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0008_auto_20160204_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('account_sync', 'Can resync Diablo 2 accounts'), ('account_sync_all', 'Can resync all Diablo 2 accounts at once'), ('character_sync', 'Can resync Diablo 2 characters'), ('character_sync_all', 'Can resync all Diablo 2 characters at once'), ('moderation_enabled', 'Can access moderation tools'), ('log_sync', 'Can sync the gameserver logs'), ('log_parse', 'Can parse the gameserver logs')), 'verbose_name': 'Account'},
        ),
    ]
