# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0013_lookup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lookup',
            new_name='LookupLog',
        ),
    ]
