# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0015_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
