# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diablo2', '0016_auto_20160209_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Account the report was generated for', max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='When the report was started')),
                ('active', models.BooleanField(default=False, help_text='Report is currently being generated')),
                ('results', models.TextField(blank=True, help_text='Report contents', null=True)),
                ('results_full', models.TextField(blank=True, help_text='Full report contents', null=True)),
                ('summary', models.TextField(blank=True, help_text='Report Summary', null=True)),
                ('ignores', models.TextField(blank=True, help_text='List of entries ignored by this report', null=True)),
                ('processed', models.TextField(blank=True, help_text='List of accounts and ips that were processed', null=True)),
                ('next', models.TextField(blank=True, help_text='List of accounts and ips to search next', null=True)),
                ('user', models.ForeignKey(help_text='User who generated this report', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
            },
        ),
    ]
