# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0017_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='depth',
            field=models.IntegerField(default=1, help_text='Depth of search'),
        ),
    ]
