# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0019_auto_20160223_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookuplog',
            old_name='results',
            new_name='num_results',
        ),
        migrations.AddField(
            model_name='lookuplog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 19, 31, 27, 632187, tzinfo=utc), help_text='When the lookup was preformed'),
            preserve_default=False,
        ),
    ]
