# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0021_lookuplog_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='checksum',
            field=models.CharField(default=' ', help_text='Character Checksum', max_length=25),
            preserve_default=False,
        ),
    ]
