# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0024_auto_20160302_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Stat recorded time')),
                ('type', models.CharField(choices=[('activity', 'Player Activity')], help_text='Stat type', max_length=25)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
            ],
            options={
                'verbose_name': 'Statistics',
            },
        ),
    ]
