# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diablo2', '0025_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
