# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diablo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Diablo 2 Account Name', max_length=25)),
                ('user_id', models.IntegerField(default=-1, help_text='Diablo 2 Account User ID')),
                ('admin', models.BooleanField(default=False, help_text='Account is admin flagged')),
                ('operator', models.BooleanField(default=False, help_text='Account is operator flagged')),
                ('locked', models.BooleanField(default=False, help_text='Account is locked')),
                ('commandgroups', models.IntegerField(default=1, help_text='Diablo 2 command groups')),
                ('lastlogin', models.DateTimeField(blank=True, help_text='Last time logged in by this account in game', null=True)),
                ('lastlogin_ip', models.CharField(blank=True, help_text='Last ip logged in from by this account in game', max_length=15, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('B', 'Banned')], default='A', help_text='Account status (Active/Banned)', max_length=1)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of this account, blank if unknown', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
