# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160107_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diablo2',
            options={'permissions': (('diablo2.sync_all', 'Can resync all Diablo 2 account data'),)},
        ),
    ]
