# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_diablo2_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diablo2',
            name='last_character_update',
            field=models.DateTimeField(blank=True, help_text='Last time character data was updated', null=True),
        ),
        migrations.AddField(
            model_name='diablo2',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Last time the account was updated from the database', null=True),
        ),
    ]
