# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160112_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diablo2Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character Name', max_length=25)),
                ('level', models.IntegerField(default=1, help_text='Character Level')),
                ('exp', models.IntegerField(default=1, help_text='Experience')),
                ('cclass', models.CharField(choices=[('SO', 'Sorceress'), ('PA', 'Paladin'), ('AM', 'Amazon'), ('NE', 'Necromancer'), ('BA', 'Barbarian'), ('AS', 'Assassin'), ('DR', 'Druid')], default='SO', help_text='Character Class', max_length=2)),
                ('difficulty', models.CharField(choices=[('NO', 'None'), ('NR', 'Normal'), ('NM', 'Nightmare'), ('HE', 'Hell')], default='NO', help_text='Character Difficulty Completed', max_length=2)),
                ('hardcore', models.BooleanField(default=False, help_text='Character is hardcore')),
                ('had_died', models.BooleanField(default=False, help_text='Character has died')),
                ('created', models.DateTimeField(help_text='Date created (Determines ladder)')),
                ('last_update', models.DateTimeField(blank=True, help_text='Last time the character was updated', null=True)),
                ('stats', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('items', models.TextField(blank=True)),
                ('quests', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Diablo2 Account', on_delete=django.db.models.deletion.CASCADE, to='accounts.Diablo2')),
            ],
        ),
    ]
