# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_diablo2character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diablo2',
            options={'permissions': (('diablo2.sync.account', 'Can resync Diablo 2 accounts'), ('diablo2.sync.account.all', 'Can resync all Diablo 2 accounts at once'), ('diablo2.sync.char', 'Can resync Diablo 2 characters'), ('diablo2.sync.char.all', 'Can resync all Diablo 2 characters at once'))},
        ),
    ]
