# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160112_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diablo2character',
            old_name='had_died',
            new_name='has_died',
        ),
        migrations.RenameField(
            model_name='diablo2character',
            old_name='items',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='diablo2character',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='diablo2character',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='diablo2character',
            name='quests',
        ),
        migrations.RemoveField(
            model_name='diablo2character',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='diablo2character',
            name='stats',
        ),
    ]
